application: corvallis-bus
version: 1
runtime: go
api_version: go1

automatic_scaling:
 max_concurrent_requests: 200
 min_idle_instances: 1
 max_idle_instances: 2
 min_pending_latency: 800ms

handlers:
- url: /.*
  script: _go_app
