package corvallisbus

import (
	"appengine/datastore"
	"time"
)

/*
  Information provided is a combination of two resources:
    * CTS connexionz database
      - https://github.com/cvanderschuere/go-connexionz
    * CTS Google Transit Feed
      - ftp://ftp.ci.corvallis.or.us/pw/Transportation/GoogleTransitFeed/Google_Transit.zip
      - Reference: https://developers.google.com/transit/gtfs/reference?csw=1

  Connexionz is a dynamic data so it will take priority

  Key information in Google Transit Google Transit Feed
    * Schedule (calendar.txt)
    * Scheduled Arrivals (stop_times.txt)
    * Route color (routes.txt)
    * Service Exceptions (calendar_dates.txt)
*/

type Route struct {
	// Key is autogenerated (string) -- No need to call directly by key

	Name           string // Treated the same as route number for most routes
	AdditionalName string // More user-friendly (ie BB_N -> Beaver Bus- North)

	Description string
	URL         string

	// https://developers.google.com/maps/documentation/utilities/polylinealgorithm
	Polyline string `datastore:",noindex"` // Needed due to length
	Color    string // Route color stored as hexadecimal

	Direction string
	Stops     []*datastore.Key // (type Stop) organized by order travelled

	Schedule Sched // Days this route runs on
}

type Sched struct {
	// Not stored directly

	Monday    bool
	Tuesday   bool
	Wednesday bool
	Thursday  bool
	Friday    bool
	Saturday  bool
	Sunday    bool

	Start time.Time // Begining of validity
	End   time.Time // End of validity
}

type Stop struct {
	// Key equal to platform number (int) -- same value posted at bus signs

	Name string

	Road           string  // Road Name
	Bearing        float64 // Bearing to road
	AdherancePoint bool    // Stops where bus will stop until scheduled departure time

	Lat  float64
	Long float64

	Arrivals []Arrival `json:,omitempty` // Used only on ETA call
}

type Arrival struct {
	//Not stored directly

	Route *datastore.Key

	Scheduled time.Time
	Expected  time.Time // Calculated from ETA when within 30 minutes of arrival

	//Destination *datastore.Key // Link to destination stop -- needed?
}

// https://developers.google.com/transit/gtfs/reference?csw=1#calendar_dates_fields
type CalendarException struct {
	// Key will be an autogenerated incomplete Key (string) -- string is faster

	Type int8
	Date time.Time
}
