package corvallisbus

import (
	"appengine/datastore"
	"time"
)

/*
  Information provided is a combination of two resources:
    * CTS connexionz database
      - https://github.com/cvanderschuere/go-connexionz
    * CTS Google Transit Feed
      - ftp://ftp.ci.corvallis.or.us/pw/Transportation/GoogleTransitFeed/Google_Transit.zip
      - Reference: https://developers.google.com/transit/gtfs/reference?csw=1

  Connexionz is a dynamic data so it will take priority

  Key information in Google Transit Google Transit Feed
    * Schedule (calendar.txt)
    * Scheduled Arrivals (stop_times.txt)
    * Route color (routes.txt)
    * Service Exceptions (calendar_dates.txt)
*/

type Route struct {
	// Key is autogenerated (string) -- No need to call directly by key

	Name           string `json:",omitempty"` // Treated the same as route number for most routes
	AdditionalName string `json:",omitempty"` // More user-friendly (ie BB_N -> Beaver Bus- North)

	Description string `json:",omitempty"`
	URL         string `json:",omitempty"`

	// https://developers.google.com/maps/documentation/utilities/polylinealgorithm
	Polyline string `datastore:",noindex" json:",omitempty"` // Needed due to length
	Color    string `json:",omitempty"`                      // Route color stored as hexadecimal

	Direction string           `json:",omitempty"`
	Stops     []*datastore.Key `json:"-"`                        // organized by order travelled
	Path      []*Stop          `datastore:"-" json:",omitempty"` // Calculated at runtime

	Start time.Time // Begining of validity of arrivals
	End   time.Time // End of validity of arrivals
}

type Stop struct {
	// Key equal to platform number (int) -- same value posted at bus signs

	Name string

	Road           string  // Road Name
	Bearing        float64 // Bearing to road
	AdherancePoint bool    // Stops where bus will stop until scheduled departure time

	Lat  float64
	Long float64
}

type Arrival struct {
	// Key will be an autogenerated incomplete Key (string) -- string is faster
	// Parent will be Stop associated with this time
	// Run query to find

	Route *datastore.Key

	Scheduled time.Duration
	//Expected  time.Duration // Calculated from ETA when within 30 minutes of arrival

	IsScheduled bool // true for values with known schedule times -- others are estimates

	// What days of the week this arrival is valid on
	Monday    bool
	Tuesday   bool
	Wednesday bool
	Thursday  bool
	Friday    bool
	Saturday  bool
	Sunday    bool
}

// https://developers.google.com/transit/gtfs/reference?csw=1#calendar_dates_fields
type CalendarException struct {
	// Key will be an autogenerated incomplete Key (string) -- string is faster

	Type int8
	Date time.Time
}
